service_ipv6: fix missing #include <platform_hal.h>
Include after <ccsp_psm_helper.h> to avoid redefinition of CHAR etc.

 | In file included from ../../../git/source/service_ipv6/service_ipv6.c:49:
 | /.../recipe-sysroot/usr/include/ccsp/platform_hal.h:103:15: error: two or more data types in declaration specifiers
 |   103 | #define CHAR  char
 |       |                ~~~
 | /.../recipe-sysroot/usr/include/ccsp/user_base.h:137:37: note: in expansion of macro 'CHAR'
 |   137 | typedef  char                       CHAR,           *PCHAR,   *LPSTR;
 |       |                                      ~~~
 | In file included from /.../recipe-sysroot/usr/include/ccsp/slap_definitions.h:84,
 |                  from /.../recipe-sysroot/usr/include/ccsp/ccsp_psm_helper.h:40,
 |                  from ../../../git/source/service_ipv6/service_ipv6.c:52:

Signed-off-by: Andre McCurdy <armccurdy@gmail.com>