service_dslite etc: optimize ds-lite service ( OFW-2175 CH7465SI-100 )
[Description]
After a power cycle, Gateway takes some time to establish IPv4 connectivity in ds-lite mode.

[Solution]
Made the following changes as part of this commit,
1. Removed the for loop which waits for dslite_enable dslite_active_1 to become 1.
   To enable ds-lite, need to enable both the values before calling service_dslite.
2. Created a static function to stop wan dhcp instead of a calling another binary.
3. Removed dslite_ipv6_frag sys variable since the support is not there in kernel.
4. Read ipv6 nameserver from sysevent.
5. IGMP proxy is not used(atleast for now). So no need to start the service
6. No need to restart Upnp service.
7. Check zebra pid then restart if needed. (didn't observe zebra crash though.)
8. Get erouter0 IP using wan6_ipaddr sysevent. It directly gets the value from dibbler-client.
   So "wan6_ipaddr" gets value before tr_erouter0_dhcpv6_client_v6addr during bootup.
9. Removed p-and-m dependency from service_ipv6
8. Removed p-and-m dependency from service_dhcp

[Testing Performed]
1. Enable dslite by using the following dmls
dmcli eRT setv Device.DSLite.InterfaceSetting.1.Enable bool true
dmcli eRT setv Device.DSLite.Enable bool true
2. Connect a lan client
3. Reboot the gateway
4. Lan client should get both ipv4/ipv6 address in ~5min
5. ping an ipv4 address from lan client and it should get icmp reply.
6. ping an ipv6 address from lan client and it should get icmp reply.

Signed-off-by: Cibil <cpankiras.contractor@libertyglobal.com>

service_ipv6: fix missing #include <platform_hal.h>

Include after <ccsp_psm_helper.h> to avoid redefinition of CHAR etc.

 | In file included from ../../../git/source/service_ipv6/service_ipv6.c:49:
 | /.../recipe-sysroot/usr/include/ccsp/platform_hal.h:103:15: error: two or more data types in declaration specifiers
 |   103 | #define CHAR  char
 |       |                ~~~
 | /.../recipe-sysroot/usr/include/ccsp/user_base.h:137:37: note: in expansion of macro 'CHAR'
 |   137 | typedef  char                       CHAR,           *PCHAR,   *LPSTR;
 |       |                                      ~~~
 | In file included from /.../recipe-sysroot/usr/include/ccsp/slap_definitions.h:84,
 |                  from /.../recipe-sysroot/usr/include/ccsp/ccsp_psm_helper.h:40,
 |                  from ../../../git/source/service_ipv6/service_ipv6.c:52:

Signed-off-by: Andre McCurdy <armccurdy@gmail.com>

service_dslite: use syscfg value "dslite_addr_fqdn_1" for static AFTR endpoint ( CH7465SI-161 OFW-2319 )

[Issue]
DSLite works even after setting an invalid endpoint name in static mode.

[Solution]
This is a regression caused by a previous commit (OFW-2175). service_dslite uses the DHCP AFTR endpoint for static mode.
As a fix, use "dslite_addr_fqdn_1" syscfg key as an AFTR endpoint for static mode.

[Testing Performed]
1. Tested in dslite DHCP mode and verified lan clients were able to establish IPv4 connection.
dmcli eRT setv Device.DSLite.InterfaceSetting.1.Enable bool true
dmcli eRT setv Device.DSLite.Enable bool true

2. Tested in dslite static mode with wrong endpointName and verified lan clients were not able to establish IPv4 connection
dmcli eRT setv Device.DSLite.InterfaceSetting.1.EndpointAssignmentPrecedence string Static
dmcli eRT setv Device.DSLite.InterfaceSetting.1.EndpointAddressTypePrecedence string FQDN
dmcli eRT setv Device.DSLite.InterfaceSetting.1.EndpointName string test_1234.com
dmcli eRT setv Device.DSLite.InterfaceSetting.1.Enable bool true
dmcli eRT setv Device.DSLite.Enable bool true

2. Tested in dslite static mode with correct endpointName and verified lan clients were able to establish IPv4 connection.
dmcli eRT setv Device.DSLite.InterfaceSetting.1.EndpointAssignmentPrecedence string Static
dmcli eRT setv Device.DSLite.InterfaceSetting.1.EndpointAddressTypePrecedence string FQDN
dmcli eRT setv Device.DSLite.InterfaceSetting.1.EndpointName string <proper-endpoint>
dmcli eRT setv Device.DSLite.Enable bool true

Signed-off-by: Cibil <cpankiras.contractor@libertyglobal.com>

service_dhcp: fix missing fclose() in getErotuerMacAddress() + misc cleanup

Signed-off-by: Andre McCurdy <armccurdy@gmail.com>