RDKCOM-4130: REFPLTB-2421 : Utopia do_compile issues in kirkstone
Reason for change :  ../../../../../../../../../rdkb/components/opensource/ccsp/Utopia/source/service_wan/service_wan.c:367:67: error: format '%x' expects argument of type 'unsigned int', but argument 5 has type 'size_t' {aka 'long unsigned int'} [-Werror=format=]
|   367 |             rc = sprintf_s(options + opt_len, (length - opt_len), "%02x", strlen(subopt_value));
changed the int format to %zu,due to strlen()
Test Procedure: 1.Verified that it is not affecting dunfell build.
                2.do_compile issues should not be observed in utopia
Risks: Low
Signed-off-by: Ssandhyarani <sirasanagandla.sandhyarani@ltts.com>

Reason for change: REFPLTB-2421 : Utopia do_compile issues in kirkstone

(cherry picked from commit 10a673f3320eaaf66a501cfb1b4eace312d7f253)
Change-Id: I053c619cba18b68c6adb376a191bb1f81038b214