RDKCOM-4237: REFPLTB-2686 :  RPI4 dunfell build is failing when new utopia i...
Reason for change: To fix the below error,
../../../../../../../../../rdkb/components/opensource/ccsp/Utopia/source/firewall/firewall.c:11697:
error: undefined reference to 'prepare_lld_dscp_rules'
../../../../../../../../../rdkb/components/opensource/ccsp/Utopia/source/firewall/firewall.c:11698:
error: undefined reference to 'prepare_dscp_rules_to_prioritized_clnt'
../../../../../../../../../rdkb/components/opensource/ccsp/Utopia/source/firewall/firewall.c:13969:
error: undefined reference to 'prepare_lld_dscp_rules'
../../../../../../../../../rdkb/components/opensource/ccsp/Utopia/source/firewall/firewall.c:13970:
error: undefined reference to 'prepare_dscp_rules_to_prioritized_clnt'
Test Procedure: utopia should be compiled successfully in rpi4 platfrom
build
Risks: Low
Signed-off-by: keerthana.p <keerthana_pandurangan@comcast.com>
Priority: P1

(cherry picked from commit 1804b074981bdcd005ae3750021d37616e87cd91)
Change-Id: I96bd6f7f5a1404bca805380529ff51cd7e7789c5